name: "hello world workflow"


on:
  push: 
    branches:
       - master
       - production


jobs: 
  hello_world:
    runs-on: ubuntu-latest
    steps:
        - name: "print Date"
          run: date
        
        - name: "print Hello world"
          run: echo "Hello world"

    
        
      
  