name: "multiSteps and multiJobs"
on: 
    push:
        branches:
            - master
            - test

    pull_request:
        branches:
            - master
        types:
            - closed 

    workflow_dispatch:
    
jobs: 
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: 
            - name: "running on master/test"
              run: echo "running on master/test"
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "running pull request for master only"
              run : echo "running pull request on for master"
            - name: "running 2nd step for pull request"
              run: date
    on-pull-request-closed: 
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "pull request closed"
              run: echo "pull request closed"
            - name: "time of closing"
              run: date
    on-workflow-dispatch: 
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "workflow_Dipatch"
              run: echo "workflow dispatch running"
        
            